### ISSUE TITLE
Could you provide the file "evaluate_eo_eop_post"? 

### ISSUE THREAD

**Issue by qingquan63** [ltl7155/fair_grad_reweighing#1]
Could you provide the file "evaluate_eo_eop_post"? There is an error about this. The code couldn't run... Thank you!

**Comment by ltl7155** [comment]
Thanks for your attention. This function is for evaluation. You can use evaluate_eo to replace evaluate_eo_eop_post. For the EOP metric, we recommend you use the fairlearn version. Note that the definition of EO in FairLearn is slightly different from our paper so we reimplement it here.
